### PR TITLE
Enable Optional CIS Scan Schedules in the User Cluster

### PR DESCRIPTION
**Pull request by chris7444**

### CODE REVIEW

**Comment by chris7444** [comment]
The UI proposes 0 0 * * * as the default schedule. I don't think running a scan every hour is realistic.In addition this schedule is configurable for the very reason that of you ask 10 people what the best schedule could be you will have 10 differentl answers


I don't understand the comment regarding the version of rancher (and how it relates to this PR). Can you put a comment on the line(s) you want me to change?

**Comment by daveolker** [comment]
rancher:
  url: https://rancher.hpe.org    # this the FQDN at which Rancher Server can be reached
  hostname: rancher.hpe.org       # generally same fqdn as the one in the url above but not necessarily
#  channel: stable                # latest, stable or alpha, default 'stable'
  **version: 2.4.3**                  # version of rancher server **2.4.3** tested, defaults to 'latest' in rancher-stable

**Comment by chris7444** [comment]
@daveolker I answered the version thing in slack.

**Comment by moyni77** [comment]
CIS scanning works a treat, just as a FYI I have raised three Jira's for [ Dev, QA and Doc] activities for this item, so we can quickly box this item off and mark done.

**Pull request merged**
