### PR TITLE
Enable cluster monitoring for Admin cluster

### PR DESCRIPTION
**Pull request by daveolker**
Add ability to disable/enable cluster monitoring for User cluster
Default for both cluster monitoring stacks is enabled

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
I don;t see how/where this code addresses the admin cluster. Can you explain ?

**Comment by daveolker** [comment]
The admin cluster is always imported with the name "local", at least in every deployment I've run in my rig.  The following API call enables monitoring for this "local" cluster:

- name: Enable monitoring in the Admin Cluster
  uri: 
    url: "{{ rancher.url }}/{{ rancher.apiversion }}/**clusters/local?action=enableMonitoring**"

**Review by ghost — APPROVED** [review]
Thank you. For some reason I did not see this line of code in the review.

**Review by moyni77 — COMMENTED** [review]
Looks good to me.

**Comment by ghost** [comment]
last comment: I am not sure an extra role was needed for that. enabling monitoring (or not) should have been handled as a variable of the existing roles.

**Pull request merged**
