### PR TITLE
SVT CSI Driver support for RKE User Cluster

### PR DESCRIPTION
**Pull request by daveolker**
Added support for SVT CSI driver when deploying RKE user cluster.  Setting the "csi_driver" variable to "svt" enables this functionality.  At this time we are installing Release Candidate 3 (RC3) of the driver.  This will get updated to the official image once it is published.  I did not make this image name a variable since our vSphere CSI driver configuration files use static values for the images and versions we tested with.

### CODE REVIEW

**Comment by daveolker** [comment]
Also, this version of the SVT CSI code includes support for creating and restoring snapshots of PVs.  I'll be adding a confluence page describing the procedure for taking a snapshot of a PV, restoring it (which also promotes it to being a First Class Disk and visible in vSphere), and verifying the restored snapshot can be used as a valid pod PV.

**Review by ghost — COMMENTED** [review]
I don;t get your explanation regarding why you hard coded the image tags. As you say these tags are subject to change and this is exactly why you should use templates (vs static files) and use variables for the tags.  we don;t want to update the repo each time a new image tag is released. When the driver is released, we can handle the variable(s) the exact same way we do for the version of rancher, rke etc.

**Review by moyni77 — COMMENTED** [review]
Hi Dave, I'm in agreement with Christophe the versioning should be controlled via vars file, I also think for pre-release, we should use a term experimental in the vars file pointing to the pre-release tagged image, with stable, and latest coming into affect which give us perfect release candidates for the svt storage plugin. In the comments we should add something in relation to PSI2x as to know which SVT version works or is missing functionality.

**Comment by daveolker** [comment]
My explanation of not using templates/variables to define the images we are pulling is that's how the current vSphere CSI driver is implemented in our playbooks.  The playbooks use hard-coded values for the various images we pull and deploy:

[core@dfo-ansible-fedora31 ~/Rancher-on-SimpliVity/playbooks/roles/csi/files (svtcsi *%)]$ grep 'image:' vsphere*
vsphere-csi-controller-ss.yaml:          image: quay.io/k8scsi/csi-attacher:v1.1.1
vsphere-csi-controller-ss.yaml:          image: gcr.io/cloud-provider-vsphere/csi/release/driver:v1.0.1
vsphere-csi-controller-ss.yaml:          image: quay.io/k8scsi/livenessprobe:v1.1.0
vsphere-csi-controller-ss.yaml:          image: gcr.io/cloud-provider-vsphere/csi/release/syncer:v1.0.1
vsphere-csi-controller-ss.yaml:          image: quay.io/k8scsi/csi-provisioner:v1.2.2
vsphere-csi-node-ds.yaml:          image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
vsphere-csi-node-ds.yaml:          image: gcr.io/cloud-provider-vsphere/csi/release/driver:v1.0.1
vsphere-csi-node-ds.yaml:          image: quay.io/k8scsi/livenessprobe:v1.1.0

Since that was the logic used for vSphere, I used the same logic for SVT:

[core@dfo-ansible-fedora31 ~/Rancher-on-SimpliVity/playbooks/roles/csi/files (svtcsi *%)]$ grep 'image:' svt*
svt-csi-controller-deployment.yaml:          image: quay.io/k8scsi/csi-attacher:v2.2.0
svt-csi-controller-deployment.yaml:          image: quay.io/k8scsi/csi-snapshotter:v2.1.0
svt-csi-controller-deployment.yaml:          image: docker.io/hpesimplivity/vsphere-csi-driver:v1.0-rc3
svt-csi-controller-deployment.yaml:          image: quay.io/k8scsi/livenessprobe:v2.0.0
svt-csi-controller-deployment.yaml:          image: docker.io/hpesimplivity/vsphere-csi-syncer:v1.0-rc3
svt-csi-controller-deployment.yaml:          image: quay.io/k8scsi/csi-provisioner:v1.6.0
svt-csi-node-ds.yaml:          image: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
svt-csi-node-ds.yaml:          image: docker.io/hpesimplivity/vsphere-csi-driver:v1.0-rc3
svt-csi-node-ds.yaml:          image: quay.io/k8scsi/livenessprobe:v2.0.0

If we are going to change these from being static files to templates and define variables for the image names/versions, my questions are these:

1. Are we going to make these changes for both vSphere and SVT?
2. Which of the above images are we going to make variables and allow customers to modify?  All images?  A subset?
3. Are we going to state in the documentation which combination of images we have tested and certified with so that if a customer decides to pull a newer or older version of an image and they run into problems they are considered unsupported?

**Comment by ghost** [comment]
Yes you are very correct, we should configure variables in the CSI vSphere as well!

**Comment by ghost** [comment]
if you don;t want the end user to change the image tag you define the vars in <role>/vars/main.yml. If you want the end user to be able to change these values, you put them in <role>/default/main.yml.
I am in favor or letting people be able to change the default values (configured in the role) ie define these variables in <role>/defaults/main.yml

one compelling reason for that is that if QA want to test various combinations of image versions (I would say "recipe"), they need to be able to specify the image tags to use. If the image tags are hard-coded like they are today, this will require an un-necessary PR. A PR would also be needed if the variables are defined in <role>/vars/main.yml (vs <role>/defaults/main.yml)

whereas if QA want to test a new "recipe" - again a recipe is a combination, hopefully functional, of image versions - they can override the default values provided by the role if the variables are defined in <role>/defaults/main.yml. Absolutely no need for creating a PR just for this purpose (this is really the very same story as changing the version of Rancher Server etc)

Also, what are the odds that the image tags for the SVT driver will change in the next few weeks. Answer=High.  We don;t want to have to make a PR just because we need to specify :vx.y instead of vy.y-rc in the manifests.

Finally, after we release, the ecosystem is evolving, so "recipes" will evolve. It is QA work that determines which recipe is working and which is not (in the case of the vSphere CSI, VMWare gives us the recipe.  And documentation can be updated to specify which recipe can be used. There is no need to change any line of code

And again, yes you are right we should do the same for the vSphere CSI driver. But this should be treated as a separate PR. You are welcome to create an issue or story.

**Review by ghost — APPROVED** [review]
All things considered and given the status of the SVT driver, the manifests themselves may be subject to change before the driver is released and configuring variables for the image tags may not be enough.  Meaning we will have to make another PR anyway.

**Comment by daveolker** [comment]
Thanks Christophe.  I opened OMNI-99012 for this redesign work and assigned it to myself.  I'll merge this PR and start working on making the images variable in the CSI role's defaults/main.yml.

**Pull request merged**
