### PR TITLE
Registry

### PR DESCRIPTION
**Pull request by ghost**
Harbor installed on the support VM. See confluence for the doc
remember the purpose of the PR is for us to have a registry that we can use for our own usage so don;t expect to see all capabilities of Harbor running out of the box, we just need to push and pull to/from a private repository

### CODE REVIEW

**Review by moyni77 — COMMENTED** [review]
Please could you remove "chris" form the vars.sample file.

**Comment by ghost** [comment]
> Please could you remove "chris" form the vars.sample file.
alan better ?

**Review by daveolker — COMMENTED** [review]
- In kits_bom.yml, should the docker_compose version be a variable rather than hard-coded at 1.26.0?

- In vault.yml.sample, the example password for vault_harbor_db_password should be "PasswordForDB" (remove extra D).

- As for the user and home directory used in the vars.yml.sample file, we've used "core" in the past and the SSH key in the vars.yml.sample file is for the "core" user.  However, looking at our published documentation, it says to create a user called "rancher" on the Ansible node and use that, even though our internal dev-docs.md file uses the "core" user.  I'm not sure when our documented recommendation switched from "core" to "rancher", but our samples should match our documentation to avoid confusion. Unless there is a good reason to switch all our examples to use the "rancher" user, my vote would be to standardize on the "core" user in our playbooks, samples, and documentation.  Either way we should be consistent. 

- In my test I'm getting the following error:

TASK [harbor : Creating project] ******************************************************************************************************************************************************
Tuesday 07 July 2020  15:17:00 -0700 (0:00:00.026)       0:08:48.990 **********
failed: [dolker-support1] (item={'project_name': 'nginxplus', 'is_public': False, 'content_trust': False, 'prevent_vul': True, 'severity': 'high', 'auto_scan': True}) => {"ansible_loop_var": "item", "changed": false, "connection": "close", "content": "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n", "content_length": "150", "content_type": "text/html", "date": "Tue, 07 Jul 2020 22:16:52 GMT", "elapsed": 0, "item": {"auto_scan": true, "content_trust": false, "is_public": false, "prevent_vul": true, "project_name": "nginxplus", "severity": "high"}, "msg": "Status code was 502 and not [201, 409]: HTTP Error 502: Bad Gateway", "redirected": false, "server": "nginx", "status": 502, "url": "https://registry.dolker.org/api/projects"}

I am able to browse to https://registry.dolker.org/api/projects and get information about the default "library" project.  I am also able to browse to https://registry.dolker.org and log into the admin portal using the password stored in my vault.

Running the registry.yml playbook manually after the initial failure worked, which leads me to believe this is timing related.  Querying the API after manually running the playbook shows both the "library" and the "nginxplus" projects.

**Comment by ghost** [comment]
@daveolker I need ansible.log and you set of variables

**Comment by ghost** [comment]
@daveolker  "version" variables
background: The new getkits.yml now supports digests and will not download a file if the existing file has the same digest. In its final form (released) **each and every file we download should come with a digest** because we don;t want to start a deployment with corrupted executables

That being said, we are now developing and I want to be able to change the version or RKE or KUBECTL etc easily if a new version comes out. That is the only reason why these files do not specify a digest at this point (but again when we release they should) BY simply changing the value of the "version" variable, I can easily make the switch **IF** there is no digest specified for the corresponding file.  While I expect we will have to test newer versions of rke, kubectl etc. I think we can stick to docker-compose version X, this is why I did not create a variable for this file. 

Actually I will go find the digest so that we can pin the version to whatever it is today.

FInally and ideally, we **may** have several kit BOMs in the future. A BOM is a recipe, the version numbers in a given recipe are pinned.

**Comment by ghost** [comment]
regarding the location of the file I don't think this is important, the files can be ANYWHERE.  I could have written /somedir/nameofyourcert.crt and this would be just fine because the people are free to drop their certs and keys wherever they want.  And this is probably why the doc replaced 'core' by 'rancher' because core is "tainted" (and would also be my last choice)

**Review by moyni77 — APPROVED** [review]
Looks good lets get this merged.

**Review by moyni77 — APPROVED** [review]
The addition of harbor_api_timeout: 300 looks fine.

**Review by daveolker — APPROVED** [review]
I ran the latest code in my rig 20 times and the registry deployed clean every time.  We can leave the vars.yml.sample user/path changes for a future PR, as I don't want that holding up this PR.

**Pull request merged**
